apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-model-sync-tts
  namespace: voice-tts
  labels:
    app.kubernetes.io/name: worker-model-sync-tts
    app.kubernetes.io/component: model-synchronizer
    app.kubernetes.io/part-of: worker-model-sync-tts
spec:
  replicas: 1
  strategy:
    type: Recreate  # 確保單一實例，避免並發衝突
  selector:
    matchLabels:
      app.kubernetes.io/name: worker-model-sync-tts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker-model-sync-tts
        app.kubernetes.io/component: model-synchronizer
        app.kubernetes.io/part-of: worker-model-sync-tts
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: worker-model-sync-tts
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: model-sync
        image: worker-model-sync-tts:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        # 從 ConfigMap 載入環境變數
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: model-sync-config
              key: AWS_REGION
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: model-sync-config
              key: S3_BUCKET_NAME
        - name: MODELS_BASE_PATH
          valueFrom:
            configMapKeyRef:
              name: model-sync-config
              key: MODELS_BASE_PATH
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: model-sync-config
              key: LOG_LEVEL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: model-sync-config
              key: NODE_ENV
        - name: SQS_UPDATE_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: model-sync-config
              key: SQS_UPDATE_QUEUE_URL
        - name: SQS_NOTIFICATION_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: model-sync-config
              key: SQS_NOTIFICATION_QUEUE_URL
        # 從 Secret 載入敏感資訊
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: models-storage
          mountPath: /models
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: worker-model-sync-tts-models-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30